#!C:\Users\KeithSatuku\OneDrive - Gulf Agency Company\Documents\zvangu\one high\rag_three\rag_three\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
